### ISSUE TITLE
Upload presentation for "Maybe monad: A practical Example"

### ISSUE THREAD

**Issue by kounelios13** [devstaff-crete/meetup45-Javascript#1]

**Comment by sourcegr** [comment]
upload no, link yes

**Comment by kounelios13** [comment]
Sounds good.Just out of curiosity why not upload?

**Comment by sourcegr** [comment]
PR sent and merged... you can view the presentation - be sure to read the disclaimer though.

To answer your question:
Because it's there anyway and I can''t really be bothered with something that has no obvious gains whatsoever :)

Is there a reason why it should be converted and uploaded ?

Also, feel free to close this issue

**Comment by kounelios13** [comment]
Thank you :)
